### ISSUE TITLE
Hyperlink structure is broken for mastodon.social profiles

### ISSUE THREAD

**Issue by drew3000** [gabipurcaru/followgraph#2]
When generating a list of accounts, the "follow" buttons don't just follow an account ,but open up a new browser tab with a hyperlink back to that Mastodon user's profile page.... or it should, but the structure is broken.

Example of what should happen:
`https://mastodon.social/@aiefel
`
Example of what does happen:
`https://mastodon.social/@aiefel@mastodon.social`

**Comment by drew3000** [comment]
I'll amend this. Many links seem to be working with this structure if they are not mastodon.social profiles. But those ones do not work.

**Comment by kittylyst** [comment]
Is it specifically mastodon.social accounts that are broken, or is it that the discovered URLs are wrong for people on the same instance as you?

E.g. if I am a mastodon.social user, I see broken hyperlinks for discovered people who are also on mastodon.social

What happens if the user is a mas.to user when they discover people who are also on mas.to?

**Comment by JcMinarro** [comment]
The problem is that the link to the users on your own instance shouldn't have the `@INSTANCE_NAME` suffix on the link.
Let's say you are on instance `myInstance.social`, your handler name is `@myUser@myInstacne.social` and you have the following suggestions: `@someNick@myInstance.social`, `@otherNick@otherInstance.social`, then, the "follow link" should be:
`https://myInstance.social/@someNick` and `https://myInstance.social/@otherNick@otherInstance.social`  

Let me try to fix it

**Comment by gabipurcaru** [comment]
should be fixed now, thanks to @JcMinarro; feel free to reopen if you still have this issue
