### ISSUE TITLE
Drop the hero image, or improve it

### ISSUE THREAD

**Issue by itamarst** [gabipurcaru/followgraph#34]
Thanks for making this useful tool!

A suggestion: "Find awesome people on Mastodon" coupled with a photo showing only young white blond people is not a great juxtaposition.

(Also I personally find AI-generated images with all the extra fingers kinda creepy, but maybe that's just my problem :grin:)

**Comment by Andre601** [comment]
Agree on the AI part...
Tho on a personal note do I find that "only young white blond people" line like a targeted hate against a group. I'm all in for inclusivity, but I feel like that it can go a bit too far with this... especially on an ai-generated image that probs got vague stuff like "Draw a group of people talking with each other" given to do stuff with...
(Also, there are multiple people with brown hair, so that blonde part is especially annoying to me)

**Comment by gabipurcaru** [comment]
@Andre601, I know your heart is probably in the right place, but I would kindly suggest that you would have better chances of success by not suggesting that your fellow netizen is doing "targeted hate", just judging on a single small comment. I'm sure @itamarst meant well here.

Let's all respect each other, we're all humans behind the keyboard :heart: (well, except for the bots, but they also deserve to be treated well)

PS. the image stays just because I'm too lazy to switch at this point. I know it's not great, but I find it hard to believe it's _that_ bad.
